language: generic
branches:
  only:
    - master
matrix:
  include:
  - os: linux
    dist: bionic
    sudo: required
    language: cpp
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-8
  - os: osx
    osx_image: xcode10.2
    language: c++
    compiler: clang

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - gcc-5
      - g++-5

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo ln -fs /usr/bin/gcc-8 /usr/local/bin/gcc; sudo ln -fs /usr/bin/g++-8 /usr/local/bin/g++; fi

script:
  - make clean all check _CXXFLAGS="-Werror"
  - ./bench
