
version: 0.1.{build}

branches:
  only:
    - master

max_jobs: 1

image:
- Visual Studio 2017

init:
  - git config --global core.autocrlf input

clone_depth: 1

hosts:
  queue-server: 127.0.0.1
  db.server.com: 127.0.0.2

platform: x64

configuration: Release

install:
  - git submodule update --init
  - git clone https://github.com/mkn/google.sparsehash -b master --depth 1 mkn
  - mv mkn/* ..
  - rm -rf mkn

build_script:
  - cp "C:\Program Files (x86)\Windows Kits\10\bin\x64\rc.exe" %CD%
  - cp %CD%\rc.exe %CD%\lib
  - SET MKN_CL_PREFERRED=1 # forces mkn to use cl even if gcc/clang are found
  # - SET MKN_COMPILE_THREADS=1 # mkn use 1 thread heap space issue
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  # doesnt exist for somereason?
  - mkdir -p "C:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt"
  - cd ..
  - mv sparsehash-c11 google
  - curl -o mkn.exe -L https://github.com/Dekken/maiken/raw/binaries/win10_x64/mkn.exe
  - SET PATH="%CD%;%PATH%"
  - SET KLOG=3
  - mkn.exe build run -a "-EHsc -bigobj -D_SPARSEHASH_CI_TESTING_" -Og 0 -dp test,bench
